version: "3"

services:
    nginx:
        image: nginx:alpine

        volumes:
            - ./mp/public:/usr/share/nginx/html
        labels:
          - "traefik.enable=true" # Enable this Service
          - "traefik.http.routers.mp.entrypoints=web-secure" # Use SSL
          - "traefik.http.routers.mp.rule=Host(`www.barrosyasociados.cl`,`barrosyasociados.cl`)" # URL that traefik match to send request to this services
          - "traefik.http.routers.mp.tls=true"
          - "traefik.http.routers.mp.tls.certresolver=le" # Use prod certificates
          - "traefik.http.services.mp.loadbalancer.server.port=80" # Port where service is listening.
#         - "traefik.http.middlewares.hugo-white.ipwhitelist.sourcerange=127.0.0.1/32,190.246.194.226"
#         - "traefik.http.routers.hugo.middlewares=hugo-white@docker"
        networks:
          - backend
        restart: unless-stopped
networks:
  backend:
    external: true
